axis_linear: 4  # Left thumb stick vertical
scale_linear: 0.5
scale_linear_turbo: 1.0

axis_angular: 3  # Left thumb stick horizontal
scale_angular: 1

enable_button: 5  # Right  trigger button
#enable_turbo_button: 14  # low digital cross button
